// client/src/pages/StringSheets.jsx
// Dev tool: export/import all game strings as CSV, edit inline with localStorage persistence.
import { useRef, useState } from 'react'
import { STRING_CATALOG, STRING_CATEGORIES, TAG_GROUPS } from '@shared/strings/gameStrings.js'
import styles from './StringSheets.module.css'

const LS_KEY = 'game_strings_overrides'
const LS_TAGS_KEY = 'game_tag_overrides'
const CSV_COLUMNS = ['category', 'key', 'default', 'value', 'tokens', 'description']

// ── localStorage helpers ──────────────────────────────────────────────────────

function loadOverrides() {
  try {
    const raw = localStorage.getItem(LS_KEY)
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

function saveOverrides(overrides) {
  localStorage.setItem(LS_KEY, JSON.stringify(overrides))
}

function loadTagOverrides() {
  try {
    const raw = localStorage.getItem(LS_TAGS_KEY)
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

function saveTagOverrides(tagOverrides) {
  localStorage.setItem(LS_TAGS_KEY, JSON.stringify(tagOverrides))
}

// ── CSV helpers ───────────────────────────────────────────────────────────────

function escapeCsvField(val) {
  const s = String(val ?? '')
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

function buildCsv(catalog, overrides) {
  const rows = [CSV_COLUMNS.map(escapeCsvField).join(',')]
  for (const entry of catalog) {
    const value = overrides[`${entry.cat}.${entry.key}`] ?? entry.default
    rows.push([
      entry.cat,
      entry.key,
      entry.default,
      value,
      (entry.tokens || []).join(' '),
      entry.desc || '',
    ].map(escapeCsvField).join(','))
  }
  return rows.join('\n')
}

function parseCsv(text) {
  // Returns array of objects keyed by first-row headers
  const lines = text.trim().split(/\r?\n/)
  if (lines.length < 2) return []

  const parseRow = (line) => {
    const fields = []
    let current = ''
    let inQuotes = false
    for (let i = 0; i < line.length; i++) {
      const ch = line[i]
      if (inQuotes) {
        if (ch === '"' && line[i + 1] === '"') { current += '"'; i++ }
        else if (ch === '"') { inQuotes = false }
        else { current += ch }
      } else {
        if (ch === '"') { inQuotes = true }
        else if (ch === ',') { fields.push(current); current = '' }
        else { current += ch }
      }
    }
    fields.push(current)
    return fields
  }

  const headers = parseRow(lines[0])
  return lines.slice(1).map(line => {
    const fields = parseRow(line)
    const obj = {}
    headers.forEach((h, i) => { obj[h.trim()] = fields[i] ?? '' })
    return obj
  })
}

function downloadFile(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function buildJsFile(catalog, overrides, tagOverrides) {
  const lines = [
    '// client/src/strings/gameStrings.js',
    '// Generated by String Sheets — paste this file to update string defaults.',
    '',
    'export const STRING_CATALOG = [',
  ]
  for (const entry of catalog) {
    const value = overrides[`${entry.cat}.${entry.key}`] ?? entry.default
    const tokens = entry.tokens ? `, tokens: ${JSON.stringify(entry.tokens)}` : ''
    const effectiveTags = getEffectiveTags(entry, tagOverrides)
    const tags = effectiveTags.length ? `, tags: ${JSON.stringify(effectiveTags)}` : ''
    lines.push(
      `  { cat: ${JSON.stringify(entry.cat)}, key: ${JSON.stringify(entry.key)}, default: ${JSON.stringify(value)}${tokens}${tags}, desc: ${JSON.stringify(entry.desc || '')} },`
    )
  }
  const catsJs = STRING_CATEGORIES.map(c => `  { id: ${JSON.stringify(c.id)}, label: ${JSON.stringify(c.label)} }`).join(',\n')
  lines.push(']', '', `export const STRING_CATEGORIES = [\n${catsJs},\n]`, '')
  lines.push('export const TAG_GROUPS = ' + JSON.stringify(TAG_GROUPS, null, 2), '')
  return lines.join('\n')
}

// Compute effective inline tags for an entry (excludes auto-tag, used for serialisation)
function getEffectiveTags(entry, tagOverrides) {
  const id = `${entry.cat}.${entry.key}`
  return tagOverrides[id] ?? entry.tags ?? []
}

// ── Component ─────────────────────────────────────────────────────────────────

const IS_DEV = import.meta.env.DEV

export default function StringSheets() {
  const [overrides, setOverrides]           = useState(loadOverrides)
  const [tagOverrides, setTagOverrides]     = useState(loadTagOverrides)
  const [filterCat, setFilterCat]           = useState('all')
  const [search, setSearch]                 = useState('')
  const [feedback, setFeedback]             = useState(null) // { msg, type }
  const [changedOnly, setChangedOnly]       = useState(false)
  const [activeTag, setActiveTag]           = useState(null)  // tag id string | null
  const [tagDropdownOpen, setTagDropdownOpen] = useState(false)
  const [openTagPickerId, setOpenTagPickerId] = useState(null) // entry id with open picker
  const [lightMode, setLightMode]           = useState(() => {
    try { return localStorage.getItem('ss_light_mode') === '1' } catch { return false }
  })
  const importRef = useRef(null)

  function toggleLightMode() {
    setLightMode(prev => {
      const next = !prev
      try { localStorage.setItem('ss_light_mode', next ? '1' : '0') } catch {}
      return next
    })
  }

  function flash(msg, type = 'ok') {
    setFeedback({ msg, type })
    setTimeout(() => setFeedback(null), 2500)
  }

  function handleChange(entry, value) {
    const id = `${entry.cat}.${entry.key}`
    setOverrides(prev => {
      const next = { ...prev }
      if (value === entry.default) {
        delete next[id]
      } else {
        next[id] = value
      }
      saveOverrides(next)
      return next
    })
  }

  function handleReset() {
    if (!confirm('Reset all values and tag edits to defaults? This clears localStorage.')) return
    localStorage.removeItem(LS_KEY)
    localStorage.removeItem(LS_TAGS_KEY)
    setOverrides({})
    setTagOverrides({})
    flash('Reset to defaults')
  }

  function handleExportCsv() {
    const csv = buildCsv(STRING_CATALOG, overrides)
    downloadFile(csv, 'game-strings.csv', 'text/csv;charset=utf-8;')
    flash('CSV downloaded')
  }

  function handleDownloadJs() {
    const js = buildJsFile(STRING_CATALOG, overrides, tagOverrides)
    downloadFile(js, 'gameStrings.js', 'text/javascript')
    flash('gameStrings.js downloaded — replace the file in client/src/strings/')
  }

  function handleCopyJs() {
    const js = buildJsFile(STRING_CATALOG, overrides, tagOverrides)
    navigator.clipboard.writeText(js).then(() => flash('Copied to clipboard'))
  }

  async function handleApplyToSource() {
    const js = buildJsFile(STRING_CATALOG, overrides, tagOverrides)
    try {
      const res = await fetch('/dev/write-file', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ file: '../shared/strings/gameStrings.js', content: js }),
      })
      const data = await res.json()
      if (data.ok) {
        flash('Applied — gameStrings.js updated')
      } else {
        flash(data.error || 'Write failed', 'err')
      }
    } catch {
      flash('Could not reach dev server', 'err')
    }
  }

  function handleImportClick() {
    importRef.current?.click()
  }

  function handleImportFile(e) {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => {
      try {
        const rows = parseCsv(ev.target.result)
        const next = { ...overrides }
        let count = 0
        for (const row of rows) {
          const cat = row.category?.trim()
          const key = row.key?.trim()
          const value = row.value?.trim()
          if (!cat || !key || value === undefined) continue
          const entry = STRING_CATALOG.find(e => e.cat === cat && e.key === key)
          if (!entry) continue
          const id = `${cat}.${key}`
          if (value === entry.default) {
            delete next[id]
          } else {
            next[id] = value
            count++
          }
        }
        saveOverrides(next)
        setOverrides(next)
        flash(`Imported — ${count} override${count !== 1 ? 's' : ''} applied`)
      } catch {
        flash('Import failed — check CSV format', 'err')
      }
    }
    reader.readAsText(file)
    e.target.value = ''
  }

  // ── Tag helpers ────────────────────────────────────────────────────────────
  // For roles/events/items entries, auto-derive the tag from the key prefix.
  // Cross-cutting tags are stored inline as entry.tags (or tagOverrides[id]).
  function getAutoTagId(entry) {
    const autoGroup = TAG_GROUPS.find(g => g.id === entry.cat)
    const prefix = entry.key.split('.')[0]
    return autoGroup?.tags.find(t => t.id === prefix)?.id ?? null
  }

  function getEntryTags(entry) {
    const explicit = getEffectiveTags(entry, tagOverrides)
    const autoTagId = getAutoTagId(entry)
    return autoTagId ? [autoTagId, ...explicit] : explicit
  }

  function handleAddTag(entry, tag) {
    const id = `${entry.cat}.${entry.key}`
    setTagOverrides(prev => {
      const current = prev[id] ?? entry.tags ?? []
      if (current.includes(tag)) return prev
      const next = { ...prev, [id]: [...current, tag] }
      saveTagOverrides(next)
      return next
    })
  }

  function handleRemoveTag(entry, tag) {
    const id = `${entry.cat}.${entry.key}`
    setTagOverrides(prev => {
      const current = prev[id] ?? entry.tags ?? []
      const updated = current.filter(t => t !== tag)
      const next = { ...prev }
      // If the updated list equals the catalog default, remove the override
      const defaultTags = entry.tags ?? []
      if (updated.length === defaultTags.length && updated.every((t, i) => t === defaultTags[i])) {
        delete next[id]
      } else {
        next[id] = updated
      }
      saveTagOverrides(next)
      return next
    })
  }

  // ── Filtered rows ─────────────────────────────────────────────────────────
  const searchLower = search.toLowerCase()
  const rows = STRING_CATALOG.filter(entry => {
    if (filterCat !== 'all' && entry.cat !== filterCat) return false
    if (changedOnly && !(`${entry.cat}.${entry.key}` in overrides)) return false
    if (activeTag && !getEntryTags(entry).includes(activeTag)) return false
    if (search) {
      return (
        entry.key.toLowerCase().includes(searchLower) ||
        entry.default.toLowerCase().includes(searchLower) ||
        (entry.desc || '').toLowerCase().includes(searchLower)
      )
    }
    return true
  })

  const changedCount = Object.keys(overrides).length

  return (
    <div className={`${styles.page} ${lightMode ? styles.pageLight : ''}`}>
      {/* ── Header ───────────────────────────────────────────────────── */}
      <header className={styles.header}>
        <div className={styles.headerLeft}>
          <h1 className={styles.title}>STRING SHEETS</h1>
          <span className={styles.count}>{rows.length} / {STRING_CATALOG.length} strings</span>
          {!IS_DEV && <span className={styles.readOnlyBadge}>READ ONLY</span>}
          {IS_DEV && changedCount > 0 && (
            <span className={styles.changedBadge}>{changedCount} changed</span>
          )}
        </div>
        <div className={styles.headerActions}>
          {feedback && (
            <span className={`${styles.feedback} ${feedback.type === 'err' ? styles.feedbackErr : ''}`}>
              {feedback.msg}
            </span>
          )}
          {IS_DEV && <button className={styles.btn} onClick={handleImportClick}>Import CSV</button>}
          <button className={styles.btn} onClick={handleExportCsv}>Export CSV</button>
          <button className={styles.btn} onClick={handleCopyJs}>Copy .js</button>
          {IS_DEV && <button className={styles.btn} onClick={handleApplyToSource}>Apply to Source</button>}
          <button className={styles.btn} onClick={handleDownloadJs}>Download .js</button>
          {IS_DEV && <button className={`${styles.btn} ${styles.btnReset}`} onClick={handleReset}>Reset</button>}
          <button className={styles.btn} onClick={toggleLightMode} title="Toggle light/dark mode">
            {lightMode ? 'NIGHT' : 'DAY'}
          </button>
        </div>
      </header>

      {/* ── Filter bar ───────────────────────────────────────────────── */}
      <div className={styles.filterBar}>
        <div className={styles.catTabs}>
          <button
            className={`${styles.catTab} ${filterCat === 'all' ? styles.catTabActive : ''}`}
            onClick={() => setFilterCat('all')}
          >
            All
          </button>
          {STRING_CATEGORIES.map(cat => (
            <button
              key={cat.id}
              className={`${styles.catTab} ${filterCat === cat.id ? styles.catTabActive : ''}`}
              onClick={() => setFilterCat(cat.id)}
            >
              {cat.label}
            </button>
          ))}
        </div>
        <div className={styles.filterRight}>
          <label className={styles.changedToggle}>
            <input
              type="checkbox"
              checked={changedOnly}
              onChange={e => setChangedOnly(e.target.checked)}
            />
            <span>Changed only</span>
          </label>

          {/* ── Tag filter ──────────────────────────────────────────── */}
          <div className={styles.tagFilter}>
            {activeTag ? (
              <button
                className={styles.activeTagChip}
                onClick={() => setActiveTag(null)}
              >
                {TAG_GROUPS.flatMap(g => g.tags).find(t => t.id === activeTag)?.label ?? activeTag}
                {' ×'}
              </button>
            ) : (
              <button
                className={`${styles.tagBtn} ${tagDropdownOpen ? styles.tagBtnOpen : ''}`}
                onClick={() => setTagDropdownOpen(o => !o)}
              >
                Filter by role / event ▾
              </button>
            )}
            {tagDropdownOpen && !activeTag && (
              <div
                className={styles.tagDropdown}
                onMouseLeave={() => setTagDropdownOpen(false)}
              >
                {TAG_GROUPS.map(group => (
                  <div key={group.id} className={styles.tagGroup}>
                    <div className={styles.tagGroupLabel}>{group.label}</div>
                    <div className={styles.tagChips}>
                      {group.tags.map(tag => (
                        <button
                          key={tag.id}
                          className={styles.tagChip}
                          onClick={() => { setActiveTag(tag.id); setTagDropdownOpen(false) }}
                        >
                          {tag.label}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          <input
            className={styles.searchInput}
            type="text"
            placeholder="Search keys, values, descriptions…"
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </div>

      {/* ── Table ────────────────────────────────────────────────────── */}
      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th className={styles.thCat}>Category</th>
              <th className={styles.thKey}>Key</th>
              <th className={styles.thDefault}>Default</th>
              <th className={styles.thValue}>Value</th>
              <th className={styles.thTokens}>Tokens</th>
              <th className={styles.thDesc}>Description</th>
              <th className={styles.thTags}>Tags</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(entry => {
              const id = `${entry.cat}.${entry.key}`
              const value = overrides[id] ?? entry.default
              const isChanged = id in overrides
              return (
                <tr key={id} className={isChanged ? styles.rowChanged : ''}>
                  <td className={styles.tdCat}>
                    <span className={`${styles.catPill} ${styles[`cat_${entry.cat}`]}`}>
                      {entry.cat}
                    </span>
                  </td>
                  <td className={styles.tdKey}>{entry.key}</td>
                  <td className={styles.tdDefault}>{entry.default}</td>
                  <td className={styles.tdValue}>
                    <input
                      className={`${styles.valueInput} ${isChanged ? styles.valueInputChanged : ''}`}
                      type="text"
                      value={value}
                      readOnly={!IS_DEV}
                      onChange={IS_DEV ? e => handleChange(entry, e.target.value) : undefined}
                    />
                  </td>
                  <td className={styles.tdTokens}>
                    {(entry.tokens || []).map(t => (
                      <code key={t} className={styles.token}>{t}</code>
                    ))}
                  </td>
                  <td className={styles.tdDesc}>{entry.desc}</td>
                  <td className={styles.tdTags}>
                    {(() => {
                      const autoTagId = getAutoTagId(entry)
                      const explicit = getEffectiveTags(entry, tagOverrides)
                      const pickerOpen = openTagPickerId === id
                      return (
                        <>
                          {autoTagId && (
                            <button
                              className={`${styles.rowTag} ${styles.autoTagChip} ${autoTagId === activeTag ? styles.rowTagActive : ''}`}
                              onClick={() => setActiveTag(autoTagId === activeTag ? null : autoTagId)}
                            >
                              {autoTagId}
                            </button>
                          )}
                          {explicit.map(tag => (
                            <button
                              key={tag}
                              className={`${styles.rowTag} ${tag === activeTag ? styles.rowTagActive : ''}`}
                              onClick={() => setActiveTag(tag === activeTag ? null : tag)}
                            >
                              {tag}
                              {IS_DEV && (
                                <span
                                  className={styles.tagRemoveBtn}
                                  onClick={e => { e.stopPropagation(); handleRemoveTag(entry, tag) }}
                                >×</span>
                              )}
                            </button>
                          ))}
                          {IS_DEV && (
                            <button
                              className={styles.addTagBtn}
                              onClick={() => setOpenTagPickerId(pickerOpen ? null : id)}
                            >+</button>
                          )}
                          {pickerOpen && (
                            <div className={styles.tagPicker}>
                              {TAG_GROUPS.map(group => {
                                const available = group.tags.filter(t => t.id !== autoTagId && !explicit.includes(t.id))
                                if (!available.length) return null
                                return (
                                  <div key={group.id}>
                                    <div className={styles.tagPickerSection}>{group.label}</div>
                                    <div className={styles.tagChips}>
                                      {available.map(t => (
                                        <button
                                          key={t.id}
                                          className={styles.tagChip}
                                          onClick={() => { handleAddTag(entry, t.id); setOpenTagPickerId(null) }}
                                        >{t.label}</button>
                                      ))}
                                    </div>
                                  </div>
                                )
                              })}
                              <input
                                className={styles.tagPickerInput}
                                type="text"
                                placeholder="custom tag…"
                                autoFocus
                                onKeyDown={e => {
                                  if (e.key === 'Enter' && e.target.value.trim()) {
                                    handleAddTag(entry, e.target.value.trim().toLowerCase().replace(/\s+/g, '-'))
                                    setOpenTagPickerId(null)
                                  }
                                  if (e.key === 'Escape') setOpenTagPickerId(null)
                                }}
                              />
                            </div>
                          )}
                        </>
                      )
                    })()}
                  </td>
                </tr>
              )
            })}
            {rows.length === 0 && (
              <tr>
                <td colSpan={7} className={styles.empty}>No strings match the current filter.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Hidden file input for CSV import */}
      <input
        ref={importRef}
        type="file"
        accept=".csv,text/csv"
        style={{ display: 'none' }}
        onChange={handleImportFile}
      />
    </div>
  )
}
