// client/src/components/slides/index.js
export { default as FallbackSlide }     from './FallbackSlide.jsx'
export { default as TitleSlide }        from './TitleSlide.jsx'
export { default as PlayerRevealSlide } from './PlayerRevealSlide.jsx'
export { default as VoteTallySlide }    from './VoteTallySlide.jsx'
export { default as GallerySlide }      from './GallerySlide.jsx'
export { default as CountdownSlide }    from './CountdownSlide.jsx'
export { default as DeathSlide }        from './DeathSlide.jsx'
export { default as VictorySlide }      from './VictorySlide.jsx'
export { default as CompositionSlide }  from './CompositionSlide.jsx'
export { default as RoleTipSlide }      from './RoleTipSlide.jsx'
export { default as ItemTipSlide }      from './ItemTipSlide.jsx'
export { default as OperatorSlide }     from './OperatorSlide.jsx'
export { default as ScoresSlide }       from './ScoresSlide.jsx'
export { default as HeartbeatSlide }    from './HeartbeatSlide.jsx'
export { default as ScoreUpdateSlide }  from './ScoreUpdateSlide.jsx'
export { default as BestSuspectSlide }  from './BestSuspectSlide.jsx'
